### PR TITLE
style: add layout for wishlist page

### PR DESCRIPTION
**Pull request by Maianki**
## Added wishlist page

Wishlist page screenshot

## Live link
https://adoring-johnson-73be28.netlify.app/pages/wishlist.html

### Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by vrinda-mahajan — APPROVED** [review]
The cards are looking awesome. Just a suggestion make the product rating color more vibrant.

**Review by VLeads — APPROVED** [review]
Awesome UI, code is good too !

**Review by anik31 — APPROVED** [review]
Everything looks good. Update the rating in cards to make it readable, it has a very low contrast ratio.

**Comment by Maianki** [comment]
> The cards are looking awesome. Just a suggestion make the product rating color more vibrant.

Will do that thanks for suggesting that.

**Comment by Maianki** [comment]
> Awesome UI, code is good too !

Thanks for reviewing.

**Comment by Maianki** [comment]
> Everything looks good. Update the rating in cards to make it readable, it has a very low contrast ratio.

Will do that thanks for informing me about it.

**Pull request merged**
