### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by Maianki**
### Login Page

Screenshot (581)

### Sign up Page

Screenshot (582)

### Live link
https://awesome-lumiere-3503ff.netlify.app/

### Thanks for reviewing my PR

### CODE REVIEW

**Review by nayyyhaa — APPROVED** [review]
Nice work! Code is also clean. You can merge it. 💯

**Comment by Maianki** [comment]
> Nice work! Code is also clean. You can merge it. 💯

Thanks for reviewing.

**Review by anik31 — APPROVED** [review]
Everything looks good to me. Nice work

**Comment by Maianki** [comment]
> Everything looks good to me. Nice work

Thanks for reviewing.

**Pull request merged**
