### PR TITLE
Add readme and media query

### PR DESCRIPTION
**Pull request by Maianki**
### README screenshot
Screenshot (612)

### Previous landing page banner
Screenshot (613)

### New Landing page banner
Screenshot (614)

## Live link for README.md and webstie

[check the live link here](https://vigilant-wing-9012a6.netlify.app/index.html)
[check the README.md here](https://github.com/Maianki/Shuttle-shopy-ecommerce/tree/add-README-and-media-query)

### CODE REVIEW

**Review by srishtigautam21 — APPROVED** [review]
The code looks clean good to merge

**Review by Anurag021 — APPROVED** [review]
All loos good to me.

**Comment by Maianki** [comment]
> The code looks clean good to merge

Thanks for reviewing.

**Comment by Maianki** [comment]
> All loos good to me.

Thanks for reviewing.

**Pull request merged**
