### PR TITLE
style : add template for product page

### PR DESCRIPTION
**Pull request by Maianki**
## Added Product listing page
The page contains
* Various filters
* Product listings

Screenshot (580)

## Live  link :
https://product-page-shopy.netlify.app/pages/product-listing-page.html

### Thanks for reviewing 😊

### CODE REVIEW

**Review by hsnice16 — APPROVED** [review]
Nice work on semantic HTML, bro. UI is neat and clean too. Great work.

**Comment by Maianki** [comment]
> Nice work on semantic HTML, bro. UI is neat and clean too. Great work.

Thanks for reviewing Himanshu.

**Review by ranitasahaa1230 — APPROVED** [review]
Looks good to merge!

**Comment by Maianki** [comment]
> Looks good to merge!

Thanks for reviewing Ranita.

**Review by samyukthasudhakar — APPROVED** [review]
Looks great. The UI looks so clean !

**Comment by Maianki** [comment]
> Looks great. The UI looks so clean !

Thanks for reviewing Samyuktha.

**Pull request merged**
