### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by Maianki**
# Added landing page for ecommerce.

## Live Link :
https://shuttle-shopy-preview.netlify.app/

### Thanks for reviewing

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
Everything is good. Suggestion - you can use svg or icons from websites instead of png icons so that you can add color & other css.

**Review by vrx29 — APPROVED** [review]
Code looks clean you can go ahead and merge.

**Comment by Maianki** [comment]
> Everything is good. Suggestion - you can use SVG or icons from websites instead of png icons so that you can add color & other CSS.

Thanks for the suggestion and for reviewing my PR. Actually, I tried finding SVG but didn't get it. Any resource you would love to share where I can get them.

**Comment by Maianki** [comment]
> Code looks clean you can go ahead and merge.

Thanks for reviewing Vineet.

**Comment by anik31** [comment]
> > Everything is good. Suggestion - you can use SVG or icons from websites instead of png icons so that you can add color & other CSS.
> 
> Thanks for the suggestion and for reviewing my PR. Actually, I tried finding SVG but didn't get it. Any resource you would love to share where I can get them.

Currently I am using font-awesome. You can check it out - https://fontawesome.com/v5/search?q=heart

**Comment by Maianki** [comment]
> > > Everything is good. Suggestion - you can use SVG or icons from websites instead of png icons so that you can add color & other CSS.
> > 
> > 
> > Thanks for the suggestion and for reviewing my PR. Actually, I tried finding SVG but didn't get it. Any resource you would love to share where I can get them.
> 
> Currently I am using font-awesome. You can check it out - https://fontawesome.com/v5/search?q=heart

Okay, I have tried font awesome but they have all solid icons. That's why I shifted. Thanks for the suggestion once again, will look around for something else.

**Pull request merged**
